### ISSUE TITLE
Fix to listaMaisModelos

### ISSUE THREAD

**Issue by alexandreornellascardeira** [cleisoncarlos/XPE_Exercicio_Modulo_01#1]
router.get("/listaMaisModelos/:order", async (req, res) => {
    try {
        // Read the car list data
        const carList = JSON.parse(await readFile(data));

        // Calculate modelsTotal for each brand
        const carsBrandAndModelsTotal = carList.reduce((acc, car) => {
            const brand = car.brand;
            const existingBrand = acc.find(item => item.brand === brand);
            if (existingBrand) {
                existingBrand.modelsTotal += car.models.length;
            } else {
                acc.push({ brand, modelsTotal: car.models.length });
            }
            return acc;
        }, []);

        // Sort by modelsTotal (descending) and name (ascending)
        carsBrandAndModelsTotal.sort((a, b) => {
            if (a.modelsTotal !== b.modelsTotal) {
                return b.modelsTotal - a.modelsTotal; // Sort by modelsTotal (descending)
            }
            return a.brand.localeCompare(b.brand); // Sort by name (ascending) for ties
        });

        // Return the requested number of elements
        const limitedResults = carsBrandAndModelsTotal.slice(0, req.params.order);
        res.send(limitedResults);
    } catch (err) {
        res.status(400).send({ error: err.message });
    }
});

**Comment by cleisoncarlos** [comment]
lgtm
